// AUTO-GENERATED from 'Drills Workbook.xlsx'. Do not edit by hand — regenerate
// when the workbook changes. tab + category = primary tab + secondary tab.
export interface SeedDrill { name: string; tab: string; category: string; }
export const DRILLS: SeedDrill[] = [
  { name: "Baton Toss", tab: "hitting", category: "Vision" },
  { name: "Wall Jugle", tab: "hitting", category: "Vision" },
  { name: "Partner 2 Ball", tab: "hitting", category: "Vision" },
  { name: "Partner 2 Ball Balance", tab: "hitting", category: "Vision" },
  { name: "Squating 2 Ball", tab: "hitting", category: "Vision" },
  { name: "Shuffling 2 Ball", tab: "hitting", category: "Vision" },
  { name: "Load 1 Ball Catch", tab: "hitting", category: "Vision" },
  { name: "Partner Ball Drop", tab: "hitting", category: "Vision" },
  { name: "Partner Ball Drop Run", tab: "hitting", category: "Vision" },
  { name: "Timing Video", tab: "hitting", category: "Vision" },
  { name: "Ring Toss", tab: "hitting", category: "Vision" },
  { name: "Under Hand Wall Juggle", tab: "hitting", category: "Vision" },
  { name: "Over Hand Wall Juggle", tab: "hitting", category: "Vision" },
  { name: "Wall Rebound Swings (Partner)", tab: "hitting", category: "Vision" },
  { name: "Colored Soft Toss", tab: "hitting", category: "Vision" },
  { name: "Colored Stops", tab: "hitting", category: "Vision" },
  { name: "Banded Bear Hugs", tab: "hitting", category: "Movement Prep" },
  { name: "Barbell Turns", tab: "hitting", category: "Movement Prep" },
  { name: "Dumbbell 1 Hand Turns", tab: "hitting", category: "Movement Prep" },
  { name: "Farm Bank Trunk Backward", tab: "hitting", category: "Movement Prep" },
  { name: "Hip Airplane", tab: "hitting", category: "Movement Prep" },
  { name: "Kettle Bell Toss (Bottom Hand)", tab: "hitting", category: "Movement Prep" },
  { name: "Kettle Bell Toss (Top Hand)", tab: "hitting", category: "Movement Prep" },
  { name: "Lumbar Spinal Moves", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Jump Back Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Rhythm Push Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Rhythm Scoop Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Sit to Stand", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Slams", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Slam Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Static Push Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Static Scoop Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Med Ball Synapse", tab: "hitting", category: "Movement Prep" },
  { name: "Plate Split Grip Turns", tab: "hitting", category: "Movement Prep" },
  { name: "Punching Bag-Tire", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Anchored Turns", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Banded Turns", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Band Pull Apart", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Cross Walks", tab: "hitting", category: "Movement Prep" },
  { name: "PVC End Range Turns", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Rapid Turns", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Side Bend", tab: "hitting", category: "Movement Prep" },
  { name: "PVC Walkout Swings", tab: "hitting", category: "Movement Prep" },
  { name: "Synapse Top Hand", tab: "hitting", category: "Movement Prep" },
  { name: "TRX Stretch", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Anchored Turns (Hitting)", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Cross Body Chop", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Door Buster", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Foguls", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Rapid Feet", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Rapid Feet on Go", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Reverse Door Buster", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bags 3s on Go", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Shuffle Turns", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bags - Introduction", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bags Shuffle on Go", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Trout Step", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Tucker Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Water Bag Walk Throughs", tab: "hitting", category: "Movement Prep" },
  { name: "Water Ball Split Grip Rapid Fire", tab: "hitting", category: "Movement Prep" },
  { name: "Water Ball Split Grip Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Water Ball Tight Oppo Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Water Ball Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Water Ball Walk Outs", tab: "hitting", category: "Movement Prep" },
  { name: "Wiffle Bat Toss", tab: "hitting", category: "Movement Prep" },
  { name: "Wrist Lock Taps", tab: "hitting", category: "Movement Prep" },
  { name: "1 Hand (Bottom)", tab: "hitting", category: "Tee" },
  { name: "1 Hand (Top)", tab: "hitting", category: "Tee" },
  { name: "Bonds Get on Top", tab: "hitting", category: "Tee" },
  { name: "Closed Stance", tab: "hitting", category: "Tee" },
  { name: "Down and Away Tee", tab: "hitting", category: "Tee" },
  { name: "Fat Grip", tab: "hitting", category: "Tee" },
  { name: "Flat Bat", tab: "hitting", category: "Tee" },
  { name: "Follow the Line", tab: "hitting", category: "Tee" },
  { name: "Griffey Finish", tab: "hitting", category: "Tee" },
  { name: "High Finish", tab: "hitting", category: "Tee" },
  { name: "Long Bat", tab: "hitting", category: "Tee" },
  { name: "Low Finish", tab: "hitting", category: "Tee" },
  { name: "Net Behind", tab: "hitting", category: "Tee" },
  { name: "Net in Front", tab: "hitting", category: "Tee" },
  { name: "Open Stance", tab: "hitting", category: "Tee" },
  { name: "Pizza Finish", tab: "hitting", category: "Tee" },
  { name: "Tony Gwynn Tee", tab: "hitting", category: "Tee" },
  { name: "1 Leg Back Leg", tab: "hitting", category: "Tee" },
  { name: "1 Leg Front Leg", tab: "hitting", category: "Tee" },
  { name: "Down & In Short Bat", tab: "hitting", category: "Tee" },
  { name: "Extreme Low Tee", tab: "hitting", category: "Tee" },
  { name: "Kneeling Bosu Ball", tab: "hitting", category: "Tee" },
  { name: "Low Trace Backs", tab: "hitting", category: "Tee" },
  { name: "PVC Foam Ball", tab: "hitting", category: "Tee" },
  { name: "2 Tee", tab: "hitting", category: "Tee" },
  { name: "4 Direction Step Back", tab: "hitting", category: "Tee" },
  { name: "Anchored Exploration", tab: "hitting", category: "Tee" },
  { name: "Backwards Resistance Band", tab: "hitting", category: "Tee" },
  { name: "Barry Larkin Drill", tab: "hitting", category: "Tee" },
  { name: "Bat Between Feet", tab: "hitting", category: "Tee" },
  { name: "Bosu Ball Knee Taps", tab: "hitting", category: "Tee" },
  { name: "Bosu Ball Swings", tab: "hitting", category: "Tee" },
  { name: "Connection Vest", tab: "hitting", category: "Tee" },
  { name: "Down Hill", tab: "hitting", category: "Tee" },
  { name: "Farm Board Back Foot", tab: "hitting", category: "Tee" },
  { name: "Farm Board Backward Slides", tab: "hitting", category: "Tee" },
  { name: "Farm Board Front Foot", tab: "hitting", category: "Tee" },
  { name: "Farm Board Front Slides", tab: "hitting", category: "Tee" },
  { name: "Forward Resistance Band Pull", tab: "hitting", category: "Tee" },
  { name: "Knee Band Resistance", tab: "hitting", category: "Tee" },
  { name: "Kneeling Start Strides", tab: "hitting", category: "Tee" },
  { name: "Land and Hold", tab: "hitting", category: "Tee" },
  { name: "Rapid Feet on Go", tab: "hitting", category: "Tee" },
  { name: "Rapid Fire", tab: "hitting", category: "Tee" },
  { name: "Rhythm 2 Tee", tab: "hitting", category: "Tee" },
  { name: "Sit to Stand", tab: "hitting", category: "Tee" },
  { name: "UpHill", tab: "hitting", category: "Tee" },
  { name: "Bounce Finish", tab: "hitting", category: "Tee" },
  { name: "Down and In", tab: "hitting", category: "Tee" },
  { name: "Heavy Bat", tab: "hitting", category: "Tee" },
  { name: "Kneeling Swings", tab: "hitting", category: "Tee" },
  { name: "Look Backs", tab: "hitting", category: "Tee" },
  { name: "Recoils", tab: "hitting", category: "Tee" },
  { name: "Seated Swing", tab: "hitting", category: "Tee" },
  { name: "Short Bat", tab: "hitting", category: "Tee" },
  { name: "Soccer Balls", tab: "hitting", category: "Tee" },
  { name: "Soccer Ball Shuffles", tab: "hitting", category: "Tee" },
  { name: "Split Grip", tab: "hitting", category: "Tee" },
  { name: "Stick Finish", tab: "hitting", category: "Tee" },
  { name: "Stop at Contact", tab: "hitting", category: "Tee" },
  { name: "Trout Steps", tab: "hitting", category: "Tee" },
  { name: "Tucker Spin Finish", tab: "hitting", category: "Tee" },
  { name: "Weighted Balls", tab: "hitting", category: "Tee" },
  { name: "Arods", tab: "hitting", category: "Tee" },
  { name: "Around the World", tab: "hitting", category: "Tee" },
  { name: "Bosu Ball Jump Backs", tab: "hitting", category: "Tee" },
  { name: "Happy Gilmores", tab: "hitting", category: "Tee" },
  { name: "Hook Em", tab: "hitting", category: "Tee" },
  { name: "Josh Donaldsons", tab: "hitting", category: "Tee" },
  { name: "Jump Backs", tab: "hitting", category: "Tee" },
  { name: "Ryan Howard Hook Em", tab: "hitting", category: "Tee" },
  { name: "Ryan Howards", tab: "hitting", category: "Tee" },
  { name: "Step Behind", tab: "hitting", category: "Tee" },
  { name: "Tall & Narrow to Stable", tab: "hitting", category: "Tee" },
  { name: "Toe Taps", tab: "hitting", category: "Tee" },
  { name: "Walking 3 Ball", tab: "hitting", category: "Tee" },
  { name: "Walk Throughs", tab: "hitting", category: "Tee" },
  { name: "2 Ball", tab: "hitting", category: "Flips" },
  { name: "Alternate FB CH", tab: "hitting", category: "Flips" },
  { name: "Fungo Drill", tab: "hitting", category: "Flips" },
  { name: "4 Direction Step Back", tab: "hitting", category: "Flips" },
  { name: "Anchored Exploration", tab: "hitting", category: "Flips" },
  { name: "Backwards Resistance Band", tab: "hitting", category: "Flips" },
  { name: "Barry Larkin Drill", tab: "hitting", category: "Flips" },
  { name: "Bat Between Feet", tab: "hitting", category: "Flips" },
  { name: "Bosu Ball Knee Taps", tab: "hitting", category: "Flips" },
  { name: "Bosu Ball Swings", tab: "hitting", category: "Flips" },
  { name: "Connection Vest", tab: "hitting", category: "Flips" },
  { name: "Down Hill", tab: "hitting", category: "Flips" },
  { name: "Farm Board Back Foot", tab: "hitting", category: "Flips" },
  { name: "Farm Board Backward Slides", tab: "hitting", category: "Flips" },
  { name: "Farm Board Front Foot", tab: "hitting", category: "Flips" },
  { name: "Farm Board Front Slides", tab: "hitting", category: "Flips" },
  { name: "Forward Resistance Band Pull", tab: "hitting", category: "Flips" },
  { name: "Knee Band Resistance", tab: "hitting", category: "Flips" },
  { name: "Kneeling Start Strides", tab: "hitting", category: "Flips" },
  { name: "Land and Hold", tab: "hitting", category: "Flips" },
  { name: "Rapid Fire", tab: "hitting", category: "Flips" },
  { name: "Reverse Barry Larkin", tab: "hitting", category: "Flips" },
  { name: "Sit to Stand", tab: "hitting", category: "Flips" },
  { name: "UpHill", tab: "hitting", category: "Flips" },
  { name: "Bounce Finish", tab: "hitting", category: "Flips" },
  { name: "Down and In", tab: "hitting", category: "Flips" },
  { name: "Heavy Bat", tab: "hitting", category: "Flips" },
  { name: "Kneeling Swings", tab: "hitting", category: "Flips" },
  { name: "Look Backs", tab: "hitting", category: "Flips" },
  { name: "Recoils", tab: "hitting", category: "Flips" },
  { name: "Seated Swing", tab: "hitting", category: "Flips" },
  { name: "Short Bat", tab: "hitting", category: "Flips" },
  { name: "Soccer Balls", tab: "hitting", category: "Flips" },
  { name: "Soccer Ball Shuffles", tab: "hitting", category: "Flips" },
  { name: "Split Grip", tab: "hitting", category: "Flips" },
  { name: "Stick Finish", tab: "hitting", category: "Flips" },
  { name: "Stop at Contact", tab: "hitting", category: "Flips" },
  { name: "Trout Steps", tab: "hitting", category: "Flips" },
  { name: "Tucker Spin Finish", tab: "hitting", category: "Flips" },
  { name: "Weighted Balls", tab: "hitting", category: "Flips" },
  { name: "Arods", tab: "hitting", category: "Flips" },
  { name: "Around the World", tab: "hitting", category: "Flips" },
  { name: "Bosu Ball Jump Backs", tab: "hitting", category: "Flips" },
  { name: "Happy Gilmores", tab: "hitting", category: "Flips" },
  { name: "Hook Em", tab: "hitting", category: "Flips" },
  { name: "Josh Donaldsons", tab: "hitting", category: "Flips" },
  { name: "Jump Backs", tab: "hitting", category: "Flips" },
  { name: "Ryan Howard Hook Em", tab: "hitting", category: "Flips" },
  { name: "Ryan Howards", tab: "hitting", category: "Flips" },
  { name: "Step Behind", tab: "hitting", category: "Flips" },
  { name: "Tall & Narrow to Stable", tab: "hitting", category: "Flips" },
  { name: "Toe Taps", tab: "hitting", category: "Flips" },
  { name: "Walking 3 Ball", tab: "hitting", category: "Flips" },
  { name: "Walk Throughs", tab: "hitting", category: "Flips" },
  { name: "1B Angle Feeds", tab: "hitting", category: "Flips" },
  { name: "1 Hand (Bottom)", tab: "hitting", category: "Flips" },
  { name: "1 Hand (Top)", tab: "hitting", category: "Flips" },
  { name: "3B Angle Feeds", tab: "hitting", category: "Flips" },
  { name: "4 Plate Around the World", tab: "hitting", category: "Flips" },
  { name: "8 Ball Contact Point", tab: "hitting", category: "Flips" },
  { name: "Bonds Get on Top", tab: "hitting", category: "Flips" },
  { name: "Closed Stance", tab: "hitting", category: "Flips" },
  { name: "Fat Grip", tab: "hitting", category: "Flips" },
  { name: "Flat Bat", tab: "hitting", category: "Flips" },
  { name: "Follow the Line", tab: "hitting", category: "Flips" },
  { name: "Griffey Finish", tab: "hitting", category: "Flips" },
  { name: "High Finish", tab: "hitting", category: "Flips" },
  { name: "Long Bat", tab: "hitting", category: "Flips" },
  { name: "Low Finish", tab: "hitting", category: "Flips" },
  { name: "Net Behind", tab: "hitting", category: "Flips" },
  { name: "Net in Front", tab: "hitting", category: "Flips" },
  { name: "Open Stance", tab: "hitting", category: "Flips" },
  { name: "Pizza Finish", tab: "hitting", category: "Flips" },
  { name: "Tennis Racket", tab: "hitting", category: "Flips" },
  { name: "1 Leg Back Leg", tab: "hitting", category: "Flips" },
  { name: "1 Leg Front Leg", tab: "hitting", category: "Flips" },
  { name: "Down & In Short Bat", tab: "hitting", category: "Flips" },
  { name: "Kneeling Bosu Ball", tab: "hitting", category: "Flips" },
  { name: "Low Trace Backs", tab: "hitting", category: "Flips" },
  { name: "PVC Foam Ball", tab: "hitting", category: "Flips" },
  { name: "Slash", tab: "hitting", category: "Flips" },
  { name: "Hit & Run", tab: "hitting", category: "Flips" },
  { name: "Get Him Over", tab: "hitting", category: "Flips" },
  { name: "Bunt", tab: "hitting", category: "Flips" },
  { name: "Infield In", tab: "hitting", category: "Flips" },
  { name: "Infield Back", tab: "hitting", category: "Flips" },
  { name: "Drive Him In", tab: "hitting", category: "Flips" },
  { name: "2-0", tab: "hitting", category: "Flips" },
  { name: "0-2", tab: "hitting", category: "Flips" },
  { name: "1-1", tab: "hitting", category: "Flips" },
  { name: "Don't Chase", tab: "hitting", category: "Flips" },
  { name: "Get Your A Swing Off", tab: "hitting", category: "Flips" },
  { name: "Low Line Drive", tab: "hitting", category: "Flips" },
  { name: "Elevate", tab: "hitting", category: "Flips" },
  { name: "Ground Ball", tab: "hitting", category: "Flips" },
  { name: "Opposite Field", tab: "hitting", category: "Flips" },
  { name: "Up the Middle", tab: "hitting", category: "Flips" },
  { name: "Pull Side", tab: "hitting", category: "Flips" },
  { name: "Pull it Fowl", tab: "hitting", category: "Flips" },
  { name: "1-2-3 Timing Count", tab: "hitting", category: "Flips" },
  { name: "Velo-Timing Change by Round", tab: "hitting", category: "Flips" },
  { name: "Velo-Timing Change by Pitch", tab: "hitting", category: "Flips" },
  { name: "Slash", tab: "hitting", category: "Batting Practice" },
  { name: "Hit & Run", tab: "hitting", category: "Batting Practice" },
  { name: "Get Him Over", tab: "hitting", category: "Batting Practice" },
  { name: "Bunt", tab: "hitting", category: "Batting Practice" },
  { name: "Infield In", tab: "hitting", category: "Batting Practice" },
  { name: "Infield Back", tab: "hitting", category: "Batting Practice" },
  { name: "Drive Him In", tab: "hitting", category: "Batting Practice" },
  { name: "2-0", tab: "hitting", category: "Batting Practice" },
  { name: "0-2", tab: "hitting", category: "Batting Practice" },
  { name: "1-1", tab: "hitting", category: "Batting Practice" },
  { name: "Don't Chase", tab: "hitting", category: "Batting Practice" },
  { name: "Get Your A Swing Off", tab: "hitting", category: "Batting Practice" },
  { name: "Low Line Drive", tab: "hitting", category: "Batting Practice" },
  { name: "Elevate", tab: "hitting", category: "Batting Practice" },
  { name: "Ground Ball", tab: "hitting", category: "Batting Practice" },
  { name: "Opposite Field", tab: "hitting", category: "Batting Practice" },
  { name: "Up the Middle", tab: "hitting", category: "Batting Practice" },
  { name: "Pull Side", tab: "hitting", category: "Batting Practice" },
  { name: "Pull it Fowl", tab: "hitting", category: "Batting Practice" },
  { name: "1-2-3 Timing Count", tab: "hitting", category: "Batting Practice" },
  { name: "Velo-Timing Change", tab: "hitting", category: "Batting Practice" },
  { name: "Alternate FB CH", tab: "hitting", category: "Batting Practice" },
  { name: "Anchored Exploration", tab: "hitting", category: "Batting Practice" },
  { name: "Backwards Resistance Band", tab: "hitting", category: "Batting Practice" },
  { name: "Barry Larkin Drill", tab: "hitting", category: "Batting Practice" },
  { name: "Bat Between Feet", tab: "hitting", category: "Batting Practice" },
  { name: "Bosu Ball Knee Taps", tab: "hitting", category: "Batting Practice" },
  { name: "Bosu Ball Swings", tab: "hitting", category: "Batting Practice" },
  { name: "Connection Vest", tab: "hitting", category: "Batting Practice" },
  { name: "Down Hill", tab: "hitting", category: "Batting Practice" },
  { name: "Farm Board Back Foot", tab: "hitting", category: "Batting Practice" },
  { name: "Farm Board Backward Slides", tab: "hitting", category: "Batting Practice" },
  { name: "Farm Board Front Foot", tab: "hitting", category: "Batting Practice" },
  { name: "Farm Board Front Slides", tab: "hitting", category: "Batting Practice" },
  { name: "Forward Resistance Band Pull", tab: "hitting", category: "Batting Practice" },
  { name: "Knee Band Resistance", tab: "hitting", category: "Batting Practice" },
  { name: "Kneeling Start Strides", tab: "hitting", category: "Batting Practice" },
  { name: "Land and Hold", tab: "hitting", category: "Batting Practice" },
  { name: "Reverse Barry Larkin", tab: "hitting", category: "Batting Practice" },
  { name: "Sit to Stand", tab: "hitting", category: "Batting Practice" },
  { name: "UpHill", tab: "hitting", category: "Batting Practice" },
  { name: "Bounce Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Down and In", tab: "hitting", category: "Batting Practice" },
  { name: "Heavy Bat", tab: "hitting", category: "Batting Practice" },
  { name: "Look Backs", tab: "hitting", category: "Batting Practice" },
  { name: "Recoils", tab: "hitting", category: "Batting Practice" },
  { name: "Short Bat", tab: "hitting", category: "Batting Practice" },
  { name: "Split Grip", tab: "hitting", category: "Batting Practice" },
  { name: "Stick Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Stop at Contact", tab: "hitting", category: "Batting Practice" },
  { name: "Trout Steps", tab: "hitting", category: "Batting Practice" },
  { name: "Tucker Spin Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Arods", tab: "hitting", category: "Batting Practice" },
  { name: "Around the World", tab: "hitting", category: "Batting Practice" },
  { name: "Bosu Ball Jump Backs", tab: "hitting", category: "Batting Practice" },
  { name: "Hook Em", tab: "hitting", category: "Batting Practice" },
  { name: "Josh Donaldsons", tab: "hitting", category: "Batting Practice" },
  { name: "Jump Backs", tab: "hitting", category: "Batting Practice" },
  { name: "Ryan Howard Hook Em", tab: "hitting", category: "Batting Practice" },
  { name: "Ryan Howards", tab: "hitting", category: "Batting Practice" },
  { name: "Step Behind", tab: "hitting", category: "Batting Practice" },
  { name: "Tall & Narrow to Stable", tab: "hitting", category: "Batting Practice" },
  { name: "Toe Taps", tab: "hitting", category: "Batting Practice" },
  { name: "Walk Throughs", tab: "hitting", category: "Batting Practice" },
  { name: "1B Angle Feeds", tab: "hitting", category: "Batting Practice" },
  { name: "3B Angle Feeds", tab: "hitting", category: "Batting Practice" },
  { name: "8 Ball Contact Point", tab: "hitting", category: "Batting Practice" },
  { name: "Bonds Get on Top", tab: "hitting", category: "Batting Practice" },
  { name: "Closed Stance", tab: "hitting", category: "Batting Practice" },
  { name: "Fat Grip", tab: "hitting", category: "Batting Practice" },
  { name: "Flat Bat", tab: "hitting", category: "Batting Practice" },
  { name: "Follow the Line", tab: "hitting", category: "Batting Practice" },
  { name: "Griffey Finish", tab: "hitting", category: "Batting Practice" },
  { name: "High Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Long Bat", tab: "hitting", category: "Batting Practice" },
  { name: "Low Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Net Behind", tab: "hitting", category: "Batting Practice" },
  { name: "Net in Front", tab: "hitting", category: "Batting Practice" },
  { name: "Open Stance", tab: "hitting", category: "Batting Practice" },
  { name: "Pizza Finish", tab: "hitting", category: "Batting Practice" },
  { name: "Low Trace Backs", tab: "hitting", category: "Batting Practice" },
  { name: "Slash", tab: "hitting", category: "Machine" },
  { name: "Hit & Run", tab: "hitting", category: "Machine" },
  { name: "Get Him Over", tab: "hitting", category: "Machine" },
  { name: "Bunt", tab: "hitting", category: "Machine" },
  { name: "Infield In", tab: "hitting", category: "Machine" },
  { name: "Infield Back", tab: "hitting", category: "Machine" },
  { name: "Drive Him In", tab: "hitting", category: "Machine" },
  { name: "2-0", tab: "hitting", category: "Machine" },
  { name: "0-2", tab: "hitting", category: "Machine" },
  { name: "1-1", tab: "hitting", category: "Machine" },
  { name: "Don't Chase", tab: "hitting", category: "Machine" },
  { name: "Get Your A Swing Off", tab: "hitting", category: "Machine" },
  { name: "Low Line Drive", tab: "hitting", category: "Machine" },
  { name: "Elevate", tab: "hitting", category: "Machine" },
  { name: "Ground Ball", tab: "hitting", category: "Machine" },
  { name: "Opposite Field", tab: "hitting", category: "Machine" },
  { name: "Up the Middle", tab: "hitting", category: "Machine" },
  { name: "Pull Side", tab: "hitting", category: "Machine" },
  { name: "Pull it Fowl", tab: "hitting", category: "Machine" },
  { name: "1-2-3 Timing Count", tab: "hitting", category: "Machine" },
  { name: "Velo-Timing Change", tab: "hitting", category: "Machine" },
  { name: "Alternate FB CH", tab: "hitting", category: "Machine" },
  { name: "Anchored Exploration", tab: "hitting", category: "Machine" },
  { name: "Backwards Resistance Band", tab: "hitting", category: "Machine" },
  { name: "Bat Between Feet", tab: "hitting", category: "Machine" },
  { name: "Bosu Ball Knee Taps", tab: "hitting", category: "Machine" },
  { name: "Bosu Ball Swings", tab: "hitting", category: "Machine" },
  { name: "Connection Vest", tab: "hitting", category: "Machine" },
  { name: "Down Hill", tab: "hitting", category: "Machine" },
  { name: "Farm Board Back Foot", tab: "hitting", category: "Machine" },
  { name: "Farm Board Backward Slides", tab: "hitting", category: "Machine" },
  { name: "Farm Board Front Foot", tab: "hitting", category: "Machine" },
  { name: "Farm Board Front Slides", tab: "hitting", category: "Machine" },
  { name: "Forward Resistance Band Pull", tab: "hitting", category: "Machine" },
  { name: "Knee Band Resistance", tab: "hitting", category: "Machine" },
  { name: "Kneeling Start Strides", tab: "hitting", category: "Machine" },
  { name: "Land and Hold", tab: "hitting", category: "Machine" },
  { name: "Sit to Stand", tab: "hitting", category: "Machine" },
  { name: "UpHill", tab: "hitting", category: "Machine" },
  { name: "Bounce Finish", tab: "hitting", category: "Machine" },
  { name: "Down and In", tab: "hitting", category: "Machine" },
  { name: "Heavy Bat", tab: "hitting", category: "Machine" },
  { name: "Look Backs", tab: "hitting", category: "Machine" },
  { name: "Recoils", tab: "hitting", category: "Machine" },
  { name: "Short Bat", tab: "hitting", category: "Machine" },
  { name: "Split Grip", tab: "hitting", category: "Machine" },
  { name: "Stick Finish", tab: "hitting", category: "Machine" },
  { name: "Stop at Contact", tab: "hitting", category: "Machine" },
  { name: "Trout Steps", tab: "hitting", category: "Machine" },
  { name: "Tucker Spin Finish", tab: "hitting", category: "Machine" },
  { name: "Arods", tab: "hitting", category: "Machine" },
  { name: "Around the World", tab: "hitting", category: "Machine" },
  { name: "Bosu Ball Jump Backs", tab: "hitting", category: "Machine" },
  { name: "Hook Em", tab: "hitting", category: "Machine" },
  { name: "Josh Donaldsons", tab: "hitting", category: "Machine" },
  { name: "Jump Backs", tab: "hitting", category: "Machine" },
  { name: "Ryan Howard Hook Em", tab: "hitting", category: "Machine" },
  { name: "Ryan Howards", tab: "hitting", category: "Machine" },
  { name: "Step Behind", tab: "hitting", category: "Machine" },
  { name: "Tall & Narrow to Stable", tab: "hitting", category: "Machine" },
  { name: "Toe Taps", tab: "hitting", category: "Machine" },
  { name: "Walk Throughs", tab: "hitting", category: "Machine" },
  { name: "1B Angle Feeds", tab: "hitting", category: "Machine" },
  { name: "3B Angle Feeds", tab: "hitting", category: "Machine" },
  { name: "8 Ball Contact Point", tab: "hitting", category: "Machine" },
  { name: "Bonds Get on Top", tab: "hitting", category: "Machine" },
  { name: "Closed Stance", tab: "hitting", category: "Machine" },
  { name: "Fat Grip", tab: "hitting", category: "Machine" },
  { name: "Flat Bat", tab: "hitting", category: "Machine" },
  { name: "Follow the Line", tab: "hitting", category: "Machine" },
  { name: "Griffey Finish", tab: "hitting", category: "Machine" },
  { name: "High Finish", tab: "hitting", category: "Machine" },
  { name: "Long Bat", tab: "hitting", category: "Machine" },
  { name: "Low Finish", tab: "hitting", category: "Machine" },
  { name: "Net Behind", tab: "hitting", category: "Machine" },
  { name: "Net in Front", tab: "hitting", category: "Machine" },
  { name: "Open Stance", tab: "hitting", category: "Machine" },
  { name: "Pizza Finish", tab: "hitting", category: "Machine" },
  { name: "Low Trace Backs", tab: "hitting", category: "Machine" },
  { name: "Hit & Run", tab: "hitting", category: "Live" },
  { name: "Get Him Over", tab: "hitting", category: "Live" },
  { name: "Bunt", tab: "hitting", category: "Live" },
  { name: "Infield In", tab: "hitting", category: "Live" },
  { name: "Infield Back", tab: "hitting", category: "Live" },
  { name: "Drive Him In", tab: "hitting", category: "Live" },
  { name: "2-0", tab: "hitting", category: "Live" },
  { name: "0-2", tab: "hitting", category: "Live" },
  { name: "1-1", tab: "hitting", category: "Live" },
  { name: "Don't Chase", tab: "hitting", category: "Live" },
  { name: "Get Your A Swing Off", tab: "hitting", category: "Live" },
  { name: "Low Line Drive", tab: "hitting", category: "Live" },
  { name: "Elevate", tab: "hitting", category: "Live" },
  { name: "Ground Ball", tab: "hitting", category: "Live" },
  { name: "Opposite Field", tab: "hitting", category: "Live" },
  { name: "Up the Middle", tab: "hitting", category: "Live" },
  { name: "Pull Side", tab: "hitting", category: "Live" },
  { name: "Pull it Fowl", tab: "hitting", category: "Live" },
  { name: "1-2-3 Timing Count", tab: "hitting", category: "Live" },
  { name: "Velo-Timing Change", tab: "hitting", category: "Live" },
  { name: "Quality AB Game", tab: "hitting", category: "Live" },
  { name: "Exercise Ball Overhead Pogos", tab: "pitching", category: "Movement Prep" },
  { name: "Field Goals", tab: "pitching", category: "Movement Prep" },
  { name: "Leopard Holds", tab: "pitching", category: "Movement Prep" },
  { name: "Med Ball Drop & Catch", tab: "pitching", category: "Movement Prep" },
  { name: "Med Ball Pogos", tab: "pitching", category: "Movement Prep" },
  { name: "Overhead Extensions", tab: "pitching", category: "Movement Prep" },
  { name: "Pec Fly", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Around the World", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Banded Rotations", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Flag Man", tab: "pitching", category: "Movement Prep" },
  { name: "PVC High Knee Turns", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Overhead", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Rotation", tab: "pitching", category: "Movement Prep" },
  { name: "PVC Routine (Full)", tab: "pitching", category: "Movement Prep" },
  { name: "Scap Reverse Fly", tab: "pitching", category: "Movement Prep" },
  { name: "Stability Recoils", tab: "pitching", category: "Movement Prep" },
  { name: "Water Bag Anchored Turns", tab: "pitching", category: "Movement Prep" },
  { name: "Water Bag Single Leg Drop Turns", tab: "pitching", category: "Movement Prep" },
  { name: "Water Bag Skenes Turns", tab: "pitching", category: "Movement Prep" },
  { name: "Water Ball Cross Body Chop", tab: "pitching", category: "Movement Prep" },
  { name: "Water Ball Knee Up Cross Body Chop", tab: "pitching", category: "Movement Prep" },
  { name: "Water Ball Windmills", tab: "pitching", category: "Movement Prep" },
  { name: "10 Toes", tab: "pitching", category: "Plyo Balls" },
  { name: "Anchored Partner Toss", tab: "pitching", category: "Plyo Balls" },
  { name: "Arm Swings", tab: "pitching", category: "Plyo Balls" },
  { name: "Catch Toss", tab: "pitching", category: "Plyo Balls" },
  { name: "Drop Steps", tab: "pitching", category: "Plyo Balls" },
  { name: "Dynamic Lasso Throw", tab: "pitching", category: "Plyo Balls" },
  { name: "Hip Rotation Ex", tab: "pitching", category: "Plyo Balls" },
  { name: "Janitor Throws", tab: "pitching", category: "Plyo Balls" },
  { name: "Quick Picks", tab: "pitching", category: "Plyo Balls" },
  { name: "Reverse Throws", tab: "pitching", category: "Plyo Balls" },
  { name: "Roll Ins", tab: "pitching", category: "Plyo Balls" },
  { name: "Stepbacks", tab: "pitching", category: "Plyo Balls" },
  { name: "Walking Windups", tab: "pitching", category: "Plyo Balls" },
  { name: "10 Toes", tab: "pitching", category: "Throw" },
  { name: "Athletic Bounce and Catch Throws", tab: "pitching", category: "Throw" },
  { name: "Athletic Drop Step Throws", tab: "pitching", category: "Throw" },
  { name: "Back Peddle Throws", tab: "pitching", category: "Throw" },
  { name: "Connection Ball Throws", tab: "pitching", category: "Throw" },
  { name: "Double Hop Throws", tab: "pitching", category: "Throw" },
  { name: "Figure 8s", tab: "pitching", category: "Throw" },
  { name: "Foam Pad Holds", tab: "pitching", category: "Throw" },
  { name: "Hip Flexion Correction Drill", tab: "pitching", category: "Throw" },
  { name: "Hover Drill", tab: "pitching", category: "Throw" },
  { name: "Hover Throws", tab: "pitching", category: "Throw" },
  { name: "K Drill", tab: "pitching", category: "Throw" },
  { name: "Kikuchi Drill", tab: "pitching", category: "Throw" },
  { name: "Kneeling Throws", tab: "pitching", category: "Throw" },
  { name: "Knee Up Hover Drill", tab: "pitching", category: "Throw" },
  { name: "Lasso Throws", tab: "pitching", category: "Throw" },
  { name: "Partner Toss Glove Work", tab: "pitching", category: "Throw" },
  { name: "Pimp Throws", tab: "pitching", category: "Throw" },
  { name: "Quick Feet", tab: "pitching", category: "Throw" },
  { name: "Rear Foot Elevated", tab: "pitching", category: "Throw" },
  { name: "Reverse Walk Throws", tab: "pitching", category: "Throw" },
  { name: "Single Leg Hop Throws", tab: "pitching", category: "Throw" },
  { name: "Single Leg Throws", tab: "pitching", category: "Throw" },
  { name: "Sitting Throws", tab: "pitching", category: "Throw" },
  { name: "Split Stance Bounce Throws", tab: "pitching", category: "Throw" },
  { name: "Split Stance Throws", tab: "pitching", category: "Throw" },
  { name: "Step Backs", tab: "pitching", category: "Throw" },
  { name: "Step Behind", tab: "pitching", category: "Throw" },
  { name: "Trevor Bauers", tab: "pitching", category: "Throw" },
  { name: "Yu Darvish Drill", tab: "pitching", category: "Throw" },
  { name: "Pitch Shape", tab: "pitching", category: "Bullpen" },
  { name: "Pitch Location", tab: "pitching", category: "Bullpen" },
  { name: "Fastball Shape", tab: "pitching", category: "Bullpen" },
  { name: "Fastball Location", tab: "pitching", category: "Bullpen" },
  { name: "Breaking Ball Shape", tab: "pitching", category: "Bullpen" },
  { name: "Breaking Ball Location", tab: "pitching", category: "Bullpen" },
  { name: "Soft Shape", tab: "pitching", category: "Bullpen" },
  { name: "Soft Location", tab: "pitching", category: "Bullpen" },
  { name: "Strike Throwing", tab: "pitching", category: "Bullpen" },
  { name: "Hand Mix", tab: "pitching", category: "Bullpen" },
  { name: "Early & Ahead", tab: "pitching", category: "Bullpen" },
  { name: "2 Strike Execution", tab: "pitching", category: "Bullpen" },
  { name: "Simulated At-Bats", tab: "pitching", category: "Bullpen" },
  { name: "No Walks", tab: "pitching", category: "Bullpen" },
  { name: "Situations", tab: "pitching", category: "Bullpen" },
  { name: "90 90 Iso Holds", tab: "pitching", category: "Post Throw" },
  { name: "Banded Bear Hugs", tab: "pitching", category: "Post Throw" },
  { name: "Band Pull Apart", tab: "pitching", category: "Post Throw" },
  { name: "Eccentric Pushup", tab: "pitching", category: "Post Throw" },
  { name: "I Y Ts", tab: "pitching", category: "Post Throw" },
  { name: "No Money", tab: "pitching", category: "Post Throw" },
  { name: "Pec Fly Iso Holds", tab: "pitching", category: "Post Throw" },
  { name: "Plyo Ball Drops", tab: "pitching", category: "Post Throw" },
  { name: "Reverse Fly Iso Hold", tab: "pitching", category: "Post Throw" },
  { name: "Scap Slides", tab: "pitching", category: "Post Throw" },
  { name: "Side Planks", tab: "pitching", category: "Post Throw" },
  { name: "Waiter Walks", tab: "pitching", category: "Post Throw" },
  { name: "1 Leg 2 Ball", tab: "catching", category: "Vision" },
  { name: "Single Leg Squat 2 Ball", tab: "catching", category: "Vision" },
  { name: "Bosu Ball 2 Ball", tab: "catching", category: "Vision" },
  { name: "Baton Toss", tab: "catching", category: "Vision" },
  { name: "Wall Jugle", tab: "catching", category: "Vision" },
  { name: "Partner 2 Ball", tab: "catching", category: "Vision" },
  { name: "Partner 2 Ball Balance", tab: "catching", category: "Vision" },
  { name: "Squating 2 Ball", tab: "catching", category: "Vision" },
  { name: "Shuffling 2 Ball", tab: "catching", category: "Vision" },
  { name: "Load 1 Ball Catch", tab: "catching", category: "Vision" },
  { name: "Partner Ball Drop", tab: "catching", category: "Vision" },
  { name: "Partner Ball Drop Run", tab: "catching", category: "Vision" },
  { name: "Timing Video", tab: "catching", category: "Vision" },
  { name: "Ring Toss", tab: "catching", category: "Vision" },
  { name: "Under Hand Wall Juggle", tab: "catching", category: "Vision" },
  { name: "Over Hand Wall Juggle", tab: "catching", category: "Vision" },
  { name: "Wall Rebound Swings (Partner)", tab: "catching", category: "Vision" },
  { name: "Colored Soft Toss", tab: "catching", category: "Vision" },
  { name: "Colored Stops", tab: "catching", category: "Vision" },
  { name: "1 Leg 3 Direction Kicks", tab: "catching", category: "Movement Prep" },
  { name: "Banded Tri-Planner Toe Taps", tab: "catching", category: "Movement Prep" },
  { name: "Block & Up Rapid Fire", tab: "catching", category: "Movement Prep" },
  { name: "Exercise Ball Core Roll Out", tab: "catching", category: "Movement Prep" },
  { name: "Exercise Ball Hamstring Curl", tab: "catching", category: "Movement Prep" },
  { name: "Knee Drag Lunge", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Around the World", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Cheating Footwork", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Footwork Push Toss", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Footwork Scoop Toss", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Shuffle Catch & Toss", tab: "catching", category: "Movement Prep" },
  { name: "PVC Cross Body Turns", tab: "catching", category: "Movement Prep" },
  { name: "Single Arm Rocking Plank", tab: "catching", category: "Movement Prep" },
  { name: "Single Leg Cone Pick Ups", tab: "catching", category: "Movement Prep" },
  { name: "Single Leg Squat Slides", tab: "catching", category: "Movement Prep" },
  { name: "Single Leg Stability Squat", tab: "catching", category: "Movement Prep" },
  { name: "Skater Jump", tab: "catching", category: "Movement Prep" },
  { name: "Two Leg Squat", tab: "catching", category: "Movement Prep" },
  { name: "Two Leg Stability Squat", tab: "catching", category: "Movement Prep" },
  { name: "Wall Ball Stability Rolls", tab: "catching", category: "Movement Prep" },
  { name: "Exercise Ball Overhead Pogos", tab: "catching", category: "Movement Prep" },
  { name: "Field Goals", tab: "catching", category: "Movement Prep" },
  { name: "Leopard Holds", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Drop & Catch", tab: "catching", category: "Movement Prep" },
  { name: "Med Ball Pogos", tab: "catching", category: "Movement Prep" },
  { name: "Overhead Extensions", tab: "catching", category: "Movement Prep" },
  { name: "Pec Fly", tab: "catching", category: "Movement Prep" },
  { name: "PVC Around the World", tab: "catching", category: "Movement Prep" },
  { name: "PVC Banded Rotations", tab: "catching", category: "Movement Prep" },
  { name: "PVC Flag Man", tab: "catching", category: "Movement Prep" },
  { name: "PVC High Knee Turns", tab: "catching", category: "Movement Prep" },
  { name: "PVC Overhead", tab: "catching", category: "Movement Prep" },
  { name: "PVC Rotation", tab: "catching", category: "Movement Prep" },
  { name: "PVC Routine (Full)", tab: "catching", category: "Movement Prep" },
  { name: "Scap Reverse Fly", tab: "catching", category: "Movement Prep" },
  { name: "Stability Recoils", tab: "catching", category: "Movement Prep" },
  { name: "Water Bag Anchored Turns", tab: "catching", category: "Movement Prep" },
  { name: "Water Bag Single Leg Drop Turns", tab: "catching", category: "Movement Prep" },
  { name: "Water Bag Skenes Turns", tab: "catching", category: "Movement Prep" },
  { name: "Water Ball Cross Body Chop", tab: "catching", category: "Movement Prep" },
  { name: "Water Ball Knee Up Cross Body Chop", tab: "catching", category: "Movement Prep" },
  { name: "Water Ball Windmills", tab: "catching", category: "Movement Prep" },
  { name: "10 Toes (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Anchored Partner Toss (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Arm Swings (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Catch Toss (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Drop Steps (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Dynamic Lasso Throw (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Hip Rotation Ex (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Janitor Throws (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Quick Picks (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Reverse Throws(Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Roll Ins (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Stepbacks (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "Walking Windups (Plyo Balls)", tab: "catching", category: "Movement Prep" },
  { name: "90 90 Iso Holds", tab: "catching", category: "Movement Prep" },
  { name: "Banded Bear Hugs", tab: "catching", category: "Movement Prep" },
  { name: "Band Pull Apart", tab: "catching", category: "Movement Prep" },
  { name: "Eccentric Pushup", tab: "catching", category: "Movement Prep" },
  { name: "I Y Ts", tab: "catching", category: "Movement Prep" },
  { name: "No Money", tab: "catching", category: "Movement Prep" },
  { name: "Pec Fly Iso Holds", tab: "catching", category: "Movement Prep" },
  { name: "Plyo Ball Drops", tab: "catching", category: "Movement Prep" },
  { name: "Reverse Fly Iso Hold", tab: "catching", category: "Movement Prep" },
  { name: "Scap Slides", tab: "catching", category: "Movement Prep" },
  { name: "Side Planks", tab: "catching", category: "Movement Prep" },
  { name: "Waiter Walks", tab: "catching", category: "Movement Prep" },
  { name: "2 Knee Blocks - Glove Up", tab: "catching", category: "Blocking" },
  { name: "2 Knee Gloves - Glove Down", tab: "catching", category: "Blocking" },
  { name: "2 Knee Yadi Taps", tab: "catching", category: "Blocking" },
  { name: "7 Ball Blocking", tab: "catching", category: "Blocking" },
  { name: "7 Ball Blocking Med Ball", tab: "catching", category: "Blocking" },
  { name: "7 Ball Blocking PVC", tab: "catching", category: "Blocking" },
  { name: "Block & Jump Forward", tab: "catching", category: "Blocking" },
  { name: "Lateral Blocks", tab: "catching", category: "Blocking" },
  { name: "Lateral Shuffle Blocks", tab: "catching", category: "Blocking" },
  { name: "Roll Blocking", tab: "catching", category: "Blocking" },
  { name: "Roll Blocking Med Ball", tab: "catching", category: "Blocking" },
  { name: "Roll Blocking PVC", tab: "catching", category: "Blocking" },
  { name: "Short Hop Blocking", tab: "catching", category: "Blocking" },
  { name: "Short Hop Blocking Med Ball", tab: "catching", category: "Blocking" },
  { name: "Short Hop Blocking PVC", tab: "catching", category: "Blocking" },
  { name: "Single Leg Squat Slide Rolls", tab: "catching", category: "Blocking" },
  { name: "Standing Blocks", tab: "catching", category: "Blocking" },
  { name: "Surprise Velocity", tab: "catching", category: "Blocking" },
  { name: "Yadi Block and Taps", tab: "catching", category: "Blocking" },
  { name: "Barehand Plyo Ball Raise", tab: "catching", category: "Receiving" },
  { name: "Bare Hand Receiving", tab: "catching", category: "Receiving" },
  { name: "Frisbee Turns", tab: "catching", category: "Receiving" },
  { name: "Glove Plyo Ball Raise/Turn", tab: "catching", category: "Receiving" },
  { name: "Mallet Turns", tab: "catching", category: "Receiving" },
  { name: "Mallet Work", tab: "catching", category: "Receiving" },
  { name: "Mix Misfires", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball 1B Angle Feeds", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball 3B Angle Feeds", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Alternate Velocity Receiving", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Alternate Weights Receiving", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Banded Bare Hand Rolls", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Banded Glove Rolls", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Barehanded Rolls", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Barehand Raise", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Barehand Short Hops", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Bottom", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Full Zone", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Glove Side", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Glove Turns", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball High Angled Feeds", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Low Angled Feeds", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Raise/Turn", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Top", tab: "catching", category: "Receiving" },
  { name: "Plyoball Receiving - Will Smith", tab: "catching", category: "Receiving" },
  { name: "Plyo Ball Turns", tab: "catching", category: "Receiving" },
  { name: "Pocket Toss", tab: "catching", category: "Receiving" },
  { name: "Resistance Band Barehand Short Hops", tab: "catching", category: "Receiving" },
  { name: "Resistance Band Glove Short Hops", tab: "catching", category: "Receiving" },
  { name: "Resistance Band Mallet Work", tab: "catching", category: "Receiving" },
  { name: "Rolls", tab: "catching", category: "Receiving" },
  { name: "Short Hops", tab: "catching", category: "Receiving" },
  { name: "Side Angled Plyo Ball Feeds", tab: "catching", category: "Receiving" },
  { name: "Straight Arm Wrist Turns", tab: "catching", category: "Receiving" },
  { name: "Strike Zone Control", tab: "catching", category: "Receiving" },
  { name: "Strike Zone Control Strings", tab: "catching", category: "Receiving" },
  { name: "Wall Rebound Receiving", tab: "catching", category: "Receiving" },
  { name: "Alternate Weights Receiving", tab: "catching", category: "Receiving" },
  { name: "Alternate Velocity Receiving", tab: "catching", category: "Receiving" },
  { name: "Bosu Ball Receiving", tab: "catching", category: "Receiving" },
  { name: "2nd Base Be Accurate", tab: "catching", category: "Throwing" },
  { name: "2nd Base Be Fast", tab: "catching", category: "Throwing" },
  { name: "3 Strep Transfers", tab: "catching", category: "Throwing" },
  { name: "Catch & Turn", tab: "catching", category: "Throwing" },
  { name: "Catch, Turn, & Transfer", tab: "catching", category: "Throwing" },
  { name: "Catch, Turn, Transfer, Catch", tab: "catching", category: "Throwing" },
  { name: "Double Shuffle Throws", tab: "catching", category: "Throwing" },
  { name: "Drop Step Throws", tab: "catching", category: "Throwing" },
  { name: "Janitor Throws", tab: "catching", category: "Throwing" },
  { name: "Med Ball Catch and Slam", tab: "catching", category: "Throwing" },
  { name: "Med Ball Cheating", tab: "catching", category: "Throwing" },
  { name: "Med Ball Footwork", tab: "catching", category: "Throwing" },
  { name: "Med Ball Footwork Catch", tab: "catching", category: "Throwing" },
  { name: "Med Ball Footwork Catch & Toss", tab: "catching", category: "Throwing" },
  { name: "Med Ball Shifts", tab: "catching", category: "Throwing" },
  { name: "Resistance Band Footwork", tab: "catching", category: "Throwing" },
  { name: "10 Toes", tab: "catching", category: "Throwing" },
  { name: "Athletic Bounce and Catch Throws", tab: "catching", category: "Throwing" },
  { name: "Athletic Drop Step Throws", tab: "catching", category: "Throwing" },
  { name: "Back Peddle Throws", tab: "catching", category: "Throwing" },
  { name: "Connection Ball Throws", tab: "catching", category: "Throwing" },
  { name: "Double Hop Throws", tab: "catching", category: "Throwing" },
  { name: "Figure 8s", tab: "catching", category: "Throwing" },
  { name: "Foam Pad Holds", tab: "catching", category: "Throwing" },
  { name: "Hip Flexion Correction Drill", tab: "catching", category: "Throwing" },
  { name: "Hover Drill", tab: "catching", category: "Throwing" },
  { name: "Hover Throws", tab: "catching", category: "Throwing" },
  { name: "K Drill", tab: "catching", category: "Throwing" },
  { name: "Kikuchi Drill", tab: "catching", category: "Throwing" },
  { name: "Kneeling Throws", tab: "catching", category: "Throwing" },
  { name: "Knee Up Hover Drill", tab: "catching", category: "Throwing" },
  { name: "Lasso Throws", tab: "catching", category: "Throwing" },
  { name: "Partner Toss Glove Work", tab: "catching", category: "Throwing" },
  { name: "Pimp Throws", tab: "catching", category: "Throwing" },
  { name: "Quick Feet", tab: "catching", category: "Throwing" },
  { name: "Rear Foot Elevated", tab: "catching", category: "Throwing" },
  { name: "Reverse Walk Throws", tab: "catching", category: "Throwing" },
  { name: "Single Leg Hop Throws", tab: "catching", category: "Throwing" },
  { name: "Single Leg Throws", tab: "catching", category: "Throwing" },
  { name: "Sitting Throws", tab: "catching", category: "Throwing" },
  { name: "Split Stance Bounce Throws", tab: "catching", category: "Throwing" },
  { name: "Split Stance Throws", tab: "catching", category: "Throwing" },
  { name: "Step Backs", tab: "catching", category: "Throwing" },
  { name: "Step Behind", tab: "catching", category: "Throwing" },
  { name: "Trevor Bauers", tab: "catching", category: "Throwing" },
  { name: "Yu Darvish Drill", tab: "catching", category: "Throwing" },
  { name: "Commit Late (Machine)", tab: "catching", category: "Machine" },
  { name: "LHP Breaking Balls (Machine)", tab: "catching", category: "Machine" },
  { name: "Read React (Machine)", tab: "catching", category: "Machine" },
  { name: "RHP Breaking Balls (Machine)", tab: "catching", category: "Machine" },
  { name: "Medball (Machine)", tab: "catching", category: "Machine" },
  { name: "PVC (Machine)", tab: "catching", category: "Machine" },
  { name: "2 Knee Blocks - Glove Up (Machine)", tab: "catching", category: "Machine" },
  { name: "2 Knee Gloves - Glove Down (Machine)", tab: "catching", category: "Machine" },
  { name: "2 Knee Yadi Taps (Machine)", tab: "catching", category: "Machine" },
  { name: "Block & Jump Forward (Machine)", tab: "catching", category: "Machine" },
  { name: "Lateral Blocks (Machine)", tab: "catching", category: "Machine" },
  { name: "Lateral Shuffle Blocks (Machine)", tab: "catching", category: "Machine" },
  { name: "Short Hop Blocking(Machine)", tab: "catching", category: "Machine" },
  { name: "Short Hop Blocking Med Ball (Machine)", tab: "catching", category: "Machine" },
  { name: "Short Hop Blocking PVC (Machine)", tab: "catching", category: "Machine" },
  { name: "Yadi Block and Taps (Machine)", tab: "catching", category: "Machine" },
  { name: "LHP 2 Seam(Machine)", tab: "catching", category: "Machine" },
  { name: "LHP 4 Seam(Machine)", tab: "catching", category: "Machine" },
  { name: "LHP Breaking Ball(Machine)", tab: "catching", category: "Machine" },
  { name: "Mix Misfires(Machine)", tab: "catching", category: "Machine" },
  { name: "Net Velocity Training(Machine)", tab: "catching", category: "Machine" },
  { name: "Pocket Toss(Machine)", tab: "catching", category: "Machine" },
  { name: "Resistance Band Short Hops(Machine)", tab: "catching", category: "Machine" },
  { name: "RHP 2 Seam(Machine)", tab: "catching", category: "Machine" },
  { name: "RHP 4 Seam(Machine)", tab: "catching", category: "Machine" },
  { name: "RHP Breaking Ball(Machine)", tab: "catching", category: "Machine" },
  { name: "Short Hops(Machine)", tab: "catching", category: "Machine" },
  { name: "Surprise Velocity(Machine)", tab: "catching", category: "Machine" },
  { name: "Resistance Band Barehand Short Hops(Machine)", tab: "catching", category: "Machine" },
  { name: "Resistance Band Glove Short Hops(Machine)", tab: "catching", category: "Machine" },
  { name: "Resistance Band Mallet Work(Machine)", tab: "catching", category: "Machine" },
  { name: "Straight Arm Wrist Turns(Machine)", tab: "catching", category: "Machine" },
  { name: "Strike Zone Control(Machine)", tab: "catching", category: "Machine" },
  { name: "Strike Zone Control Strings(Machine)", tab: "catching", category: "Machine" },
  { name: "1 Leg 2 Ball", tab: "infield", category: "Vision" },
  { name: "Single Leg Squat 2 Ball", tab: "infield", category: "Vision" },
  { name: "Bosu Ball 2 Ball", tab: "infield", category: "Vision" },
  { name: "Baton Toss", tab: "infield", category: "Vision" },
  { name: "Wall Jugle", tab: "infield", category: "Vision" },
  { name: "Partner 2 Ball", tab: "infield", category: "Vision" },
  { name: "Partner 2 Ball Balance", tab: "infield", category: "Vision" },
  { name: "Squating 2 Ball", tab: "infield", category: "Vision" },
  { name: "Shuffling 2 Ball", tab: "infield", category: "Vision" },
  { name: "Load 1 Ball Catch", tab: "infield", category: "Vision" },
  { name: "Partner Ball Drop", tab: "infield", category: "Vision" },
  { name: "Partner Ball Drop Run", tab: "infield", category: "Vision" },
  { name: "Timing Video", tab: "infield", category: "Vision" },
  { name: "Ring Toss", tab: "infield", category: "Vision" },
  { name: "Under Hand Wall Juggle", tab: "infield", category: "Vision" },
  { name: "Over Hand Wall Juggle", tab: "infield", category: "Vision" },
  { name: "Wall Rebound Swings (Partner)", tab: "infield", category: "Vision" },
  { name: "Colored Soft Toss", tab: "infield", category: "Vision" },
  { name: "Colored Stops", tab: "infield", category: "Vision" },
  { name: "Exercise Ball Overhead Pogos", tab: "infield", category: "Movement Prep" },
  { name: "Field Goals", tab: "infield", category: "Movement Prep" },
  { name: "Leopard Holds", tab: "infield", category: "Movement Prep" },
  { name: "Med Ball Drop & Catch", tab: "infield", category: "Movement Prep" },
  { name: "Med Ball Pogos", tab: "infield", category: "Movement Prep" },
  { name: "Overhead Extensions", tab: "infield", category: "Movement Prep" },
  { name: "Pec Fly", tab: "infield", category: "Movement Prep" },
  { name: "PVC Around the World", tab: "infield", category: "Movement Prep" },
  { name: "PVC Banded Rotations", tab: "infield", category: "Movement Prep" },
  { name: "PVC Flag Man", tab: "infield", category: "Movement Prep" },
  { name: "PVC High Knee Turns", tab: "infield", category: "Movement Prep" },
  { name: "PVC Overhead", tab: "infield", category: "Movement Prep" },
  { name: "PVC Rotation", tab: "infield", category: "Movement Prep" },
  { name: "PVC Routine (Full)", tab: "infield", category: "Movement Prep" },
  { name: "Scap Reverse Fly", tab: "infield", category: "Movement Prep" },
  { name: "Stability Recoils", tab: "infield", category: "Movement Prep" },
  { name: "Water Bag Anchored Turns", tab: "infield", category: "Movement Prep" },
  { name: "Water Bag Single Leg Drop Turns", tab: "infield", category: "Movement Prep" },
  { name: "Water Bag Skenes Turns", tab: "infield", category: "Movement Prep" },
  { name: "Water Ball Cross Body Chop", tab: "infield", category: "Movement Prep" },
  { name: "Water Ball Knee Up Cross Body Chop", tab: "infield", category: "Movement Prep" },
  { name: "Water Ball Windmills", tab: "infield", category: "Movement Prep" },
  { name: "10 Toes (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Anchored Partner Toss (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Arm Swings (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Catch Toss (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Drop Steps (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Dynamic Lasso Throw (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Hip Rotation Ex (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Janitor Throws (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Quick Picks (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Reverse Throws(Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Roll Ins (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Stepbacks (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "Walking Windups (Plyo Balls)", tab: "infield", category: "Movement Prep" },
  { name: "90 90 Iso Holds", tab: "infield", category: "Movement Prep" },
  { name: "Banded Bear Hugs", tab: "infield", category: "Movement Prep" },
  { name: "Band Pull Apart", tab: "infield", category: "Movement Prep" },
  { name: "Eccentric Pushup", tab: "infield", category: "Movement Prep" },
  { name: "I Y Ts", tab: "infield", category: "Movement Prep" },
  { name: "No Money", tab: "infield", category: "Movement Prep" },
  { name: "Pec Fly Iso Holds", tab: "infield", category: "Movement Prep" },
  { name: "Plyo Ball Drops", tab: "infield", category: "Movement Prep" },
  { name: "Reverse Fly Iso Hold", tab: "infield", category: "Movement Prep" },
  { name: "Scap Slides", tab: "infield", category: "Movement Prep" },
  { name: "Side Planks", tab: "infield", category: "Movement Prep" },
  { name: "Waiter Walks", tab: "infield", category: "Movement Prep" },
  { name: "10 Toes", tab: "infield", category: "Throw" },
  { name: "Athletic Bounce and Catch Throws", tab: "infield", category: "Throw" },
  { name: "Athletic Drop Step Throws", tab: "infield", category: "Throw" },
  { name: "Back Peddle Throws", tab: "infield", category: "Throw" },
  { name: "Connection Ball Throws", tab: "infield", category: "Throw" },
  { name: "Double Hop Throws", tab: "infield", category: "Throw" },
  { name: "Figure 8s", tab: "infield", category: "Throw" },
  { name: "Foam Pad Holds", tab: "infield", category: "Throw" },
  { name: "Hip Flexion Correction Drill", tab: "infield", category: "Throw" },
  { name: "Hover Drill", tab: "infield", category: "Throw" },
  { name: "Hover Throws", tab: "infield", category: "Throw" },
  { name: "K Drill", tab: "infield", category: "Throw" },
  { name: "Kikuchi Drill", tab: "infield", category: "Throw" },
  { name: "Kneeling Throws", tab: "infield", category: "Throw" },
  { name: "Knee Up Hover Drill", tab: "infield", category: "Throw" },
  { name: "Lasso Throws", tab: "infield", category: "Throw" },
  { name: "Partner Toss Glove Work", tab: "infield", category: "Throw" },
  { name: "Pimp Throws", tab: "infield", category: "Throw" },
  { name: "Quick Feet", tab: "infield", category: "Throw" },
  { name: "Rear Foot Elevated", tab: "infield", category: "Throw" },
  { name: "Reverse Walk Throws", tab: "infield", category: "Throw" },
  { name: "Single Leg Hop Throws", tab: "infield", category: "Throw" },
  { name: "Single Leg Throws", tab: "infield", category: "Throw" },
  { name: "Sitting Throws", tab: "infield", category: "Throw" },
  { name: "Split Stance Bounce Throws", tab: "infield", category: "Throw" },
  { name: "Split Stance Throws", tab: "infield", category: "Throw" },
  { name: "Step Backs", tab: "infield", category: "Throw" },
  { name: "Step Behind", tab: "infield", category: "Throw" },
  { name: "Trevor Bauers", tab: "infield", category: "Throw" },
  { name: "Yu Darvish Drill", tab: "infield", category: "Throw" },
  { name: "1 Leg 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Single Leg Squat 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Bosu Ball 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Baton Toss", tab: "outfield", category: "Vision" },
  { name: "Wall Jugle", tab: "outfield", category: "Vision" },
  { name: "Partner 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Partner 2 Ball Balance", tab: "outfield", category: "Vision" },
  { name: "Squating 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Shuffling 2 Ball", tab: "outfield", category: "Vision" },
  { name: "Load 1 Ball Catch", tab: "outfield", category: "Vision" },
  { name: "Partner Ball Drop", tab: "outfield", category: "Vision" },
  { name: "Partner Ball Drop Run", tab: "outfield", category: "Vision" },
  { name: "Timing Video", tab: "outfield", category: "Vision" },
  { name: "Ring Toss", tab: "outfield", category: "Vision" },
  { name: "Under Hand Wall Juggle", tab: "outfield", category: "Vision" },
  { name: "Over Hand Wall Juggle", tab: "outfield", category: "Vision" },
  { name: "Wall Rebound Swings (Partner)", tab: "outfield", category: "Vision" },
  { name: "Colored Soft Toss", tab: "outfield", category: "Vision" },
  { name: "Colored Stops", tab: "outfield", category: "Vision" },
  { name: "Exercise Ball Overhead Pogos", tab: "outfield", category: "Movement Prep" },
  { name: "Field Goals", tab: "outfield", category: "Movement Prep" },
  { name: "Leopard Holds", tab: "outfield", category: "Movement Prep" },
  { name: "Med Ball Drop & Catch", tab: "outfield", category: "Movement Prep" },
  { name: "Med Ball Pogos", tab: "outfield", category: "Movement Prep" },
  { name: "Overhead Extensions", tab: "outfield", category: "Movement Prep" },
  { name: "Pec Fly", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Around the World", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Banded Rotations", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Flag Man", tab: "outfield", category: "Movement Prep" },
  { name: "PVC High Knee Turns", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Overhead", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Rotation", tab: "outfield", category: "Movement Prep" },
  { name: "PVC Routine (Full)", tab: "outfield", category: "Movement Prep" },
  { name: "Scap Reverse Fly", tab: "outfield", category: "Movement Prep" },
  { name: "Stability Recoils", tab: "outfield", category: "Movement Prep" },
  { name: "Water Bag Anchored Turns", tab: "outfield", category: "Movement Prep" },
  { name: "Water Bag Single Leg Drop Turns", tab: "outfield", category: "Movement Prep" },
  { name: "Water Bag Skenes Turns", tab: "outfield", category: "Movement Prep" },
  { name: "Water Ball Cross Body Chop", tab: "outfield", category: "Movement Prep" },
  { name: "Water Ball Knee Up Cross Body Chop", tab: "outfield", category: "Movement Prep" },
  { name: "Water Ball Windmills", tab: "outfield", category: "Movement Prep" },
  { name: "10 Toes (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Anchored Partner Toss (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Arm Swings (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Catch Toss (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Drop Steps (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Dynamic Lasso Throw (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Hip Rotation Ex (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Janitor Throws (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Quick Picks (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Reverse Throws(Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Roll Ins (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Stepbacks (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "Walking Windups (Plyo Balls)", tab: "outfield", category: "Movement Prep" },
  { name: "90 90 Iso Holds", tab: "outfield", category: "Movement Prep" },
  { name: "Banded Bear Hugs", tab: "outfield", category: "Movement Prep" },
  { name: "Band Pull Apart", tab: "outfield", category: "Movement Prep" },
  { name: "Eccentric Pushup", tab: "outfield", category: "Movement Prep" },
  { name: "I Y Ts", tab: "outfield", category: "Movement Prep" },
  { name: "No Money", tab: "outfield", category: "Movement Prep" },
  { name: "Pec Fly Iso Holds", tab: "outfield", category: "Movement Prep" },
  { name: "Plyo Ball Drops", tab: "outfield", category: "Movement Prep" },
  { name: "Reverse Fly Iso Hold", tab: "outfield", category: "Movement Prep" },
  { name: "Scap Slides", tab: "outfield", category: "Movement Prep" },
  { name: "Side Planks", tab: "outfield", category: "Movement Prep" },
  { name: "Waiter Walks", tab: "outfield", category: "Movement Prep" },
  { name: "10 Toes", tab: "outfield", category: "Throw" },
  { name: "Athletic Bounce and Catch Throws", tab: "outfield", category: "Throw" },
  { name: "Athletic Drop Step Throws", tab: "outfield", category: "Throw" },
  { name: "Back Peddle Throws", tab: "outfield", category: "Throw" },
  { name: "Connection Ball Throws", tab: "outfield", category: "Throw" },
  { name: "Double Hop Throws", tab: "outfield", category: "Throw" },
  { name: "Figure 8s", tab: "outfield", category: "Throw" },
  { name: "Foam Pad Holds", tab: "outfield", category: "Throw" },
  { name: "Hip Flexion Correction Drill", tab: "outfield", category: "Throw" },
  { name: "Hover Drill", tab: "outfield", category: "Throw" },
  { name: "Hover Throws", tab: "outfield", category: "Throw" },
  { name: "K Drill", tab: "outfield", category: "Throw" },
  { name: "Kikuchi Drill", tab: "outfield", category: "Throw" },
  { name: "Kneeling Throws", tab: "outfield", category: "Throw" },
  { name: "Knee Up Hover Drill", tab: "outfield", category: "Throw" },
  { name: "Lasso Throws", tab: "outfield", category: "Throw" },
  { name: "Partner Toss Glove Work", tab: "outfield", category: "Throw" },
  { name: "Pimp Throws", tab: "outfield", category: "Throw" },
  { name: "Quick Feet", tab: "outfield", category: "Throw" },
  { name: "Rear Foot Elevated", tab: "outfield", category: "Throw" },
  { name: "Reverse Walk Throws", tab: "outfield", category: "Throw" },
  { name: "Single Leg Hop Throws", tab: "outfield", category: "Throw" },
  { name: "Single Leg Throws", tab: "outfield", category: "Throw" },
  { name: "Sitting Throws", tab: "outfield", category: "Throw" },
  { name: "Split Stance Bounce Throws", tab: "outfield", category: "Throw" },
  { name: "Split Stance Throws", tab: "outfield", category: "Throw" },
  { name: "Step Backs", tab: "outfield", category: "Throw" },
  { name: "Step Behind", tab: "outfield", category: "Throw" },
  { name: "Trevor Bauers", tab: "outfield", category: "Throw" },
  { name: "Yu Darvish Drill", tab: "outfield", category: "Throw" },
];
